apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 2
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 2        # how many pods we can add at a time
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: soberservicesguy/portfolio-images:ecommerce_orders_20
        resources:
          limits:
            cpu: "200m"
            memory: "300Mi"
        ports:
        - containerPort: 5005
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: ecommerce-mongodb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: ecommerce-mongodb-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: ecommerce-mongodb-configmap
              key: MONGO_SERVER
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: orders
  ports:
    - protocol: TCP
      targetPort: 5005
      port: 5005