apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 2
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 2        # how many pods we can add at a time
  #     maxUnavailable: 0
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: soberservicesguy/portfolio-images:ecommerce_products
        resources:
          limits:
            cpu: "200m"
            memory: "300Mi"
        ports:
        - containerPort: 5003
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: appointment-mongodb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: appointment-mongodb-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: appointment-mongodb-configmap
              key: MONGO_SERVER
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: products
  ports:
    - protocol: TCP
      targetPort: 5003
      port: 5003